"""add batch daily logs table

Revision ID: 57cd71656cca
Revises: a1b2c3d4e5f6
Create Date: 2026-08-14 20:14:24.310579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57cd71656cca'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'batch_daily_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('batch_id', sa.Integer(), nullable=False),
        sa.Column('log_date', sa.DateTime(), nullable=False),
        sa.Column('action_taken', sa.String(), nullable=False),
        sa.Column('condition', sa.String(), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['batch_id'], ['fermentation_batches.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_daily_logs_batch_id'), 'batch_daily_logs', ['batch_id'], unique=False)
    op.create_index(op.f('ix_batch_daily_logs_id'), 'batch_daily_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_batch_daily_logs_id'), table_name='batch_daily_logs')
    op.drop_index(op.f('ix_batch_daily_logs_batch_id'), table_name='batch_daily_logs')
    op.drop_table('batch_daily_logs')
    # ### end Alembic commands ###
