"""add tutorial_url to product_templates

Revision ID: c615f60f015a
Revises: 57cd71656cca
Create Date: 2026-09-01 14:35:35.888563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c615f60f015a'
down_revision: Union[str, Sequence[str], None] = '57cd71656cca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fermentation_batches', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_fermentation_batches_status'), 'fermentation_batches', ['status'], unique=False)
    op.create_index(op.f('ix_fermentation_batches_user_id'), 'fermentation_batches', ['user_id'], unique=False)
    op.add_column('fermentation_logs', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('fermentation_logs', 'batch_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_fermentation_logs_batch_id'), 'fermentation_logs', ['batch_id'], unique=False)
    op.add_column('product_recommendations', sa.Column('user_id', sa.String(), nullable=True))
    op.alter_column('product_recommendations', 'batch_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_product_recommendations_user_id'), 'product_recommendations', ['user_id'], unique=False)
    op.create_foreign_key(None, 'product_recommendations', 'users', ['user_id'], ['id'])
    op.add_column('product_templates', sa.Column('tutorial_url', sa.String(), nullable=True))
    op.add_column('product_templates', sa.Column('regional_average_price', sa.Float(), nullable=True))
    op.alter_column('roadmap_progress', 'batch_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('roadmap_progress', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roadmap_progress', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('roadmap_progress', 'batch_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('product_templates', 'regional_average_price')
    op.drop_column('product_templates', 'tutorial_url')
    op.drop_constraint(None, 'product_recommendations', type_='foreignkey')
    op.drop_index(op.f('ix_product_recommendations_user_id'), table_name='product_recommendations')
    op.alter_column('product_recommendations', 'batch_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('product_recommendations', 'user_id')
    op.drop_index(op.f('ix_fermentation_logs_batch_id'), table_name='fermentation_logs')
    op.alter_column('fermentation_logs', 'batch_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('fermentation_logs', 'updated_at')
    op.drop_index(op.f('ix_fermentation_batches_user_id'), table_name='fermentation_batches')
    op.drop_index(op.f('ix_fermentation_batches_status'), table_name='fermentation_batches')
    op.alter_column('fermentation_batches', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
